---
# Workspace Setup Playbook
# Creates a development workspace structure with sample files

- name: Create Development Workspace
  hosts: all
  gather_facts: yes
  
  vars:
    workspace_base: "~/ansible_workspace"
    timestamp: "{{ ansible_date_time.iso8601_basic_short }}"
  
  tasks:
    - name: Display workspace setup information
      ansible.builtin.debug:
        msg: |
          ====================================
          WORKSPACE SETUP
          ====================================
          Creating workspace at: {{ workspace_base }}
          Timestamp: {{ timestamp }}
          User: {{ ansible_user_id }}
    
    - name: Create main workspace directory
      ansible.builtin.file:
        path: "{{ workspace_base }}"
        state: directory
        mode: '0755'
    
    - name: Create project subdirectories
      ansible.builtin.file:
        path: "{{ workspace_base }}/{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - projects
        - scripts
        - logs
        - backups
        - docs
        - config
    
    - name: Create a sample README file
      ansible.builtin.copy:
        dest: "{{ workspace_base }}/README.md"
        content: |
          # Ansible Workspace
          
          Created by: Snake and CogWheel
          Date: {{ ansible_date_time.date }}
          Time: {{ ansible_date_time.time }}
          
          ## Directory Structure
          
          - `projects/` - Your project files
          - `scripts/` - Automation scripts
          - `logs/` - Log files
          - `backups/` - Backup files
          - `docs/` - Documentation
          - `config/` - Configuration files
          
          ## System Information
          
          - Hostname: {{ ansible_hostname }}
          - OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
          - Architecture: {{ ansible_architecture }}
        mode: '0644'
    
    - name: Create a sample shell script (Unix/Linux/Mac)
      ansible.builtin.copy:
        dest: "{{ workspace_base }}/scripts/hello.sh"
        content: |
          #!/bin/bash
          # Sample script created by Ansible
          
          echo "Hello from {{ ansible_hostname }}!"
          echo "Current date: $(date)"
          echo "Current user: $(whoami)"
          echo "Workspace: {{ workspace_base }}"
        mode: '0755'
      when: ansible_system != "Win32NT"
    
    - name: Create a sample PowerShell script (Windows)
      ansible.builtin.copy:
        dest: "{{ workspace_base }}/scripts/hello.ps1"
        content: |
          # Sample PowerShell script created by Ansible
          
          Write-Host "Hello from {{ ansible_hostname }}!"
          Write-Host "Current date: $(Get-Date)"
          Write-Host "Current user: $env:USERNAME"
          Write-Host "Workspace: {{ workspace_base }}"
        mode: '0644'
      when: ansible_system == "Win32NT"
    
    - name: Create a sample log file
      ansible.builtin.copy:
        dest: "{{ workspace_base }}/logs/setup_{{ timestamp }}.log"
        content: |
          Workspace Setup Log
          ====================
          Date: {{ ansible_date_time.date }}
          Time: {{ ansible_date_time.time }}
          User: {{ ansible_user_id }}
          Hostname: {{ ansible_hostname }}
          
          Setup completed successfully!
        mode: '0644'
    
    - name: Create a configuration file
      ansible.builtin.copy:
        dest: "{{ workspace_base }}/config/settings.conf"
        content: |
          # Workspace Configuration
          # Generated by Ansible on {{ ansible_date_time.date }}
          
          WORKSPACE_ROOT={{ workspace_base }}
          USER={{ ansible_user_id }}
          HOSTNAME={{ ansible_hostname }}
          OS={{ ansible_distribution }}
          CREATED={{ ansible_date_time.iso8601 }}
        mode: '0644'
    
    - name: List created workspace structure (Unix/Linux/Mac)
      ansible.builtin.command: ls -la {{ workspace_base }}
      register: workspace_listing_unix
      changed_when: false
      failed_when: false
      when: ansible_system != "Win32NT"
    
    - name: List created workspace structure (Windows)
      ansible.builtin.win_shell: Get-ChildItem -Path "{{ workspace_base }}" | Format-Table -AutoSize
      register: workspace_listing_windows
      changed_when: false
      failed_when: false
      when: ansible_system == "Win32NT"
    
    - name: Find all created files and directories
      ansible.builtin.find:
        paths: "{{ workspace_base }}"
        recurse: yes
        file_type: any
      register: workspace_files
    
    - name: Display workspace contents (Unix/Linux/Mac)
      ansible.builtin.debug:
        msg: |
          ====================================
          WORKSPACE CREATED SUCCESSFULLY
          ====================================
          Location: {{ workspace_base }}
          
          {{ workspace_listing_unix.stdout }}
          
          Total items created: {{ workspace_files.matched }}
      when: 
        - ansible_system != "Win32NT"
        - workspace_listing_unix is defined
    
    - name: Display workspace contents (Windows)
      ansible.builtin.debug:
        msg: |
          ====================================
          WORKSPACE CREATED SUCCESSFULLY
          ====================================
          Location: {{ workspace_base }}
          
          Total items created: {{ workspace_files.matched }}
      when: ansible_system == "Win32NT"
    
    - name: Final summary
      ansible.builtin.debug:
        msg: |
          ====================================
          SETUP COMPLETE
          ====================================
          ✅ Workspace directory created
          ✅ 6 subdirectories created
          ✅ Sample files generated
          ✅ Scripts and configs ready
          
          Your workspace is ready at: {{ workspace_base }}
          
          To explore: cd {{ workspace_base }}

